run_name: unet_blur
batch_size: 12
optim_lr: 0.0001
device: cuda:0
log_dir: 'logs/${run_name}'
model_name: basic_unet
val_every: 20
save_every: 40
inf_size: 64
in_channels: 4
modality:
- 0
- 1
- 2
- 3
out_channels: 4
feature_size: 16
hidden_size: 768
mlp_dim: 3072
num_heads: 12
pos_embed: perceptron
norm_name: instance
dropout_rate: 0.0
pretrained: false
path_to_pretrain: null
path_to_checkpoint: null
smooth_nr: 0.0
smooth_dr: 1.0e-06
sw_batch_size: 1
infer_overlap: 0.5
optim_name: adamw
optim_weight_decay: 1.0e-05
momentum: 0.99
lrschedule_name: warmup_linear
warmup_epochs: 10
max_epochs: 100000
data_dir: ~/dev/data/msd/
json_name: dataset.json
spacing: [1.0, 1.0, 1.0]
a_min: 175.0
a_max: 250.0
b_min: 0.0
b_max: 1.0
RandFlipd_prob: 0.2
RandRotate90d_prob: 0.2
RandScaleIntensityd_prob: 0.1
RandShiftIntensityd_prob: 0.1
gauss_noise_prob: 0.0
gauss_noise_std: 0.05
gauss_smooth_prob: 1.0
gauss_smooth_std: [0.25, 1.5]
n_workers: 0
cache_num: 390